name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Usar directamente la acción de SAST desde el repositorio jgutierrezdtt/Secure
      - name: Run SAST Analysis
        uses: jgutierrezdtt/Secure/.github/workflows/sast-scan.yml@master
        with:
          scan_target: ${{ github.workspace }}
          output_file: sast-results.json
      
      # Usar directamente la acción de análisis de dependencias desde el repositorio
      - name: Run Dependency Analysis
        uses: jgutierrezdtt/Secure/.github/workflows/dependency-check.yml@master
        with:
          project_dir: ${{ github.workspace }}
          output_file: dependency-results.json
      
      # Usar directamente la acción de escaneo de secretos desde el repositorio
      - name: Run Secret Scan
        uses: jgutierrezdtt/Secure/.github/workflows/secret-scan.yml@master
        with:
          scan_dir: ${{ github.workspace }}
          output_file: secrets-results.json
      
      # Usar la acción para generar el informe HTML
      - name: Generate Security Report
        uses: jgutierrezdtt/Secure/.github/workflows/generate-report.yml@master
        with:
          sast_results: ${{ github.workspace }}/sast-results.json
          dependency_results: ${{ github.workspace }}/dependency-results.json
          secrets_results: ${{ github.workspace }}/secrets-results.json
          output_html: ${{ github.workspace }}/security-report.html
      
      - name: Upload security report
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: |
            ${{ github.workspace }}/sast-results.json
            ${{ github.workspace }}/dependency-results.json
            ${{ github.workspace }}/secrets-results.json
            ${{ github.workspace }}/security-report.html