name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Permite ejecutar el workflow manualmente desde la interfaz de GitHub

jobs:
  # Checkout del código para tenerlo disponible para los flujos de trabajo llamados
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    outputs:
      workspace: ${{ github.workspace }}

  # Trabajo para el análisis SAST
  sast-analysis:
    needs: prepare
    uses: jgutierrezdtt/Secure/.github/workflows/sast-scan.yml@master
    with:
      scan_target: ${{ needs.prepare.outputs.workspace }}
      output_file: sast-results.json

  # Trabajo para el análisis de dependencias
  dependency-analysis:
    needs: prepare
    uses: jgutierrezdtt/Secure/.github/workflows/dependency-check.yml@master
    with:
      project_dir: ${{ needs.prepare.outputs.workspace }}
      output_file: dependency-results.json

  # Trabajo para el escaneo de secretos
  secret-scan:
    needs: prepare
    uses: jgutierrezdtt/Secure/.github/workflows/secret-scan.yml@master
    with:
      scan_dir: ${{ needs.prepare.outputs.workspace }}
      output_file: secrets-results.json

  # Trabajo para generar el informe HTML
  generate-report:
    needs: [sast-analysis, dependency-analysis, secret-scan]
    uses: jgutierrezdtt/Secure/.github/workflows/generate-report.yml@master
    with:
      sast_results: ${{ needs.sast-analysis.outputs.result_path }}
      dependency_results: ${{ needs.dependency-analysis.outputs.result_path }}
      secrets_results: ${{ needs.secret-scan.outputs.result_path }}
      output_html: security-report.html

  # Trabajo para subir los informes como artefactos
  upload-reports:
    needs: generate-report
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
        
      - name: Upload security report
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: |
            sast-results.json
            dependency-results.json
            secrets-results.json
            security-report.html